// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Api.Data;

#nullable disable

namespace ProductCatalog.Api.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261002131222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ProductCatalog.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Upright and stereo microscopes",
                            Name = "Microscopes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Objectives, eyepieces and cameras",
                            Name = "Optics"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Illumination, covers and calibration",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.IdSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("IdSequences");

                    b.HasData(
                        new
                        {
                            Name = "Product",
                            LastValue = 100008
                        });
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("Stock");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 100001,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upright microscope used in teaching labs.",
                            Name = "Primo Star",
                            Price = 2450.00m,
                            Stock = 6,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100002,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact stereo microscope with an integrated camera.",
                            Name = "Stemi 305",
                            Price = 1890.00m,
                            Stock = 4,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100003,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Microscope camera for routine color imaging.",
                            Name = "Axiocam 208 color",
                            Price = 3200.00m,
                            Stock = 2,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100004,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-resolution objective.",
                            Name = "Plan-Apochromat 20x",
                            Price = 4100.50m,
                            Stock = 8,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100005,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Calibration slide, 1 mm scale.",
                            Name = "Stage micrometer",
                            Price = 85.00m,
                            Stock = 40,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100006,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft cover for an upright stand.",
                            Name = "Dust cover",
                            Price = 29.90m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100007,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Replacement transmitted-light source.",
                            Name = "LED illuminator",
                            Price = 210.00m,
                            Stock = 0,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 100008,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Widefield eyepiece.",
                            Name = "Eyepiece 10x/23",
                            Price = 160.00m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Product", b =>
                {
                    b.HasOne("ProductCatalog.Api.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
